//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagement.Data
{
    using System;
    using System.Collections.Generic;

    public partial class Product : EntityBase
    {
        public Product()
        {
            this.ProductFeature = new HashSet<ProductFeature>();
            this.ProductImage = new HashSet<ProductImage>();
        }
    
        public int Id { get; set; }
        public int CategoryId { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<ProductFeature> ProductFeature { get; set; }
        public virtual ICollection<ProductImage> ProductImage { get; set; }
    }
}
